name : CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
          - name: checkout code
            uses: actions/checkout@v3

          - name: setup python
            uses: actions/setup-python@v4
            with:
              python-version: '3.12'

          - name: Cache pip dependencies
            uses: actions/cache@v3
            with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Install DVC and DagsHub Support
            run: |
              pip install "dvc[http]" dagshub

          - name: Configure DVC Remote and Pull Data
            env:
              DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
              DAGSHUB_TOKEN: ${{ secrets.PERSONALITY_TEST }}
            run: |
              dvc remote modify origin --local auth basic
              dvc remote modify origin --local user $DAGSHUB_USERNAME
              dvc remote modify origin --local password $DAGSHUB_TOKEN
              dvc pull  # <-- This is what fetches the data from your DagsHub

          - name: run pipeline
            env:
              PERSONALITY_TEST: ${{ secrets.PERSONALITY_TEST }}
            run: |
              dvc repro